'use client';
// import type { Metadata } from "next";
// import HeaderComponent from "./components/headerComponent";
import { AuthProvider } from '@/shared/guard/authContext';
import Navigation from './home/components/navigation';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Next.js</title>
      </head>
      <body className="bg-gray-100 text-gray-900 antialiased dark:bg-gray-900 dark:text-gray-100">
        <AuthProvider>
          <Navigation />

          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
